# Application name
spring.application.name = Film-hook

# Profile
<<<<<<< HEAD
spring.profiles.active = dev
=======
spring.profiles.active = local

#Diesh
#Gooo
>>>>>>> 9037effa (Check without push)
