package com.annular.filmhook.model;

public enum MediaFileCategory {

    Gallery,
    Stories,
    Post,
    Audition,
    Project,
    Image,
    Video,
    PanCard,
    AadhaarCard,
    ProfilePic,
    CoverPic,
    MarketPlace,
    ShootingLocation,
    Chat,
    MarketPlaceChat,
    ShootingLocationChat,
    oneMinuteVideo,
    govermentId,
    shootingGovermentId,
    shootingLocationImage,
    shootingLocationVerificationVideo,
    shootingLocationImageProof,
    AuditionScript,
    Promote,
    AuditionProfilePicture,
    ShootingLocationReview,
}
